In [1]:
import pandas as pd
import numpy as np
import math
import warnings
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection  import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.datasets import load_boston
from sklearn.linear_model import LinearRegression

In [2]:
warnings.filterwarnings("ignore")

In [3]:
housing_boston = load_boston()
X = housing_boston.data     # data
y = housing_boston.target   # label
feature_names = housing_boston.feature_names  #feature_names

In [4]:
X = pd.DataFrame(X)

In [5]:
X.columns = feature_names

In [25]:
#划分训练集测试集
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2795)

In [26]:
# 对数据进行归一化处理
standarScaler_X = StandardScaler()
standarScaler_X.fit(X_train)
X_train_std = standarScaler_X.transform(X_train)
X_test_std = standarScaler_X.transform(X_test)

In [27]:
# 目标值进行标准化
standarScaler_y = StandardScaler()
standarScaler_y.fit(y_train.reshape(-1,1))
y_train_std = standarScaler_y.transform(y_train.reshape(-1,1))
y_test_std = standarScaler_y.transform(y_test.reshape(-1,1))

In [28]:
lr = LinearRegression()
lr.fit(X_train_std, y_train_std)

LinearRegression()

In [29]:
#回归系数
lr.coef_

array([[-8.93993261e-02,  1.12886057e-01,  4.70878375e-02,
         4.37548022e-02, -2.25657263e-01,  3.21344637e-01,
        -3.50089035e-04, -3.07199003e-01,  2.69203047e-01,
        -2.23859300e-01, -2.21548361e-01,  9.42209510e-02,
        -4.02969163e-01]])

In [30]:
# 预测
y_predict = standarScaler_y.inverse_transform(lr.predict(X_test_std))#预测出来后需要逆标准化将数据转化回原数值
y_predict

array([[18.27743986],
       [28.84384186],
       [18.07363831],
       [31.77445177],
       [25.42337993],
       [21.81407842],
       [ 9.51564464],
       [19.35460157],
       [23.64869701],
       [23.2086198 ],
       [20.01958884],
       [23.82383441],
       [11.40094493],
       [26.45564187],
       [26.09241195],
       [16.53605132],
       [31.57845481],
       [16.96151428],
       [16.20445571],
       [24.54430894],
       [33.06436755],
       [24.37522386],
       [27.29564978],
       [24.62611645],
       [22.16190787],
       [24.59725765],
       [18.8702199 ],
       [33.34543444],
       [15.46720169],
       [18.90204489],
       [29.26066366],
       [23.97146264],
       [ 8.36936357],
       [13.23792452],
       [18.64113956],
       [17.40475053],
       [ 5.2605087 ],
       [19.21510804],
       [17.29078936],
       [24.27874241],
       [27.87871367],
       [17.91939954],
       [21.45883109],
       [23.52418401],
       [29.13227978],
       [18

In [24]:
y_test

array([18.2, 22.8, 14.5, 27. , 19.4, 20.7, 17.8, 12.5, 23. , 19.4, 27.5,
       20.1, 12.7, 22. , 22.6, 13.4, 50. , 19.5, 17.4, 21.4, 30.3, 22.2,
       24.8, 24.4, 20.6, 50. , 16.8, 36.4, 18.9, 19.9, 22.5, 24.4,  5. ,
       13.9, 16.1, 17.1,  7.4, 16.4, 13. , 22.6, 23.9, 18.7, 16.1, 20.3,
       24.3, 12.1, 21.9, 21.2, 23.3, 17.9, 24. , 14.1, 17.1, 23.9, 23.1,
       26.4, 15.1, 10.9, 25. , 14.9, 18.5, 35.4, 10.2, 42.3, 10.9, 13.8,
       11. , 18.3, 16.5, 23.1, 20.5, 46.7, 36.2, 21.4, 36.1, 35.1, 15.2,
       24.5, 29.6, 20.9, 17.8, 15. , 26.2, 18.5, 33.2, 20. , 31.2, 20.4,
       20.9, 22.9, 19. , 22.8, 37.6, 50. , 17.5, 14.6, 21.2, 16.8, 23.7,
       21.4,  8.8, 21.7])